### ISSUE TITLE
DEV Not Updating All Files Correctly

### ISSUE THREAD

**Issue by zzimbler** [JourneyUnknown/journeyunknown-wordpress-theme#10]

**Comment by ctrimm** [comment]
So, there were two things that I did to fix this issue.
- **Always bump the CSS version number** when you're ready for changes to go live. Version # is at the top of the style.css file.
- I turned off a caching plugin as well. Lol. I think this was the root cause.

You can check that the correct theme is being pulled in by checking on the dev.journeyunknown admin dashboard. In order to check, go to Appearance > Themes -> Then check 'Theme Details' for the active theme and make sure the version got bumped to what you are expecting it to be.
